### ISSUE TITLE
Train my own dataset

### ISSUE THREAD

**Issue by samlong-yang** [hizhangp/yolo_tensorflow#1]
Hi, I trained my own dataset with the yolo_tensorflow, but get the following  error:
`InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [539] rhs shape= [1470]
         [[Node: save/Assign_49 = Assign[T=DT_FLOAT, _class=["loc:@Variable_53"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](Variable_53, save/RestoreV2_49/_1)]]
`
I don't know how to do with this error

**Comment by hizhangp** [comment]
@samlong-yang Did you change `cfg.CLASSES` into binary classification? If so, you should avoid restoring layer `self.fc_32` from checkpoint, since they have different channels (539 VS 1470).

**Comment by samlong-yang** [comment]
Thanks for your suggestion, I've fixed the bug!

**Comment by pakrchen** [comment]
Hi, how to avoid restoring layer self.fc_32? Thanks!

**Comment by StefaniaTp** [comment]
@pakrchen 
Hi, did you solve the problem?

**Comment by mldm4** [comment]
I am facing the same issue, could anyone share how to avoid restoring layer self.fc_32? Thanks!
