### ISSUE TITLE
error loading the weight file (successfully trained with own dataset and saved)when doing the test

### ISSUE THREAD

**Issue by CompilerBian** [hizhangp/yolo_tensorflow#10]
I have successfully trained the model with my own dataset(which have two classes)and saved the weight file. But when I loaded the saved model to conduct testing, something wrong with the weight file
```
/core/util/tensor_slice_reader.cc:95] Could not open ./data/weights/save.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?

```
The error appears in the line:
```
self.saver.restore(self.sess, self.weights_file)
```
The version of tensorflow I am currently using is 1.2. I'm not sure if it's the version problem(I have searched on the Internet for this error and found the same problems related to the version of tensorflow ). Could you help me with this issue and how to restore weight files which have been trained?

**Comment by hizhangp** [comment]
It is mainly because of the incompatible between` write_version` `V1` and `V2` in [`tf.traion.Saver`](https://www.tensorflow.org/api_docs/python/tf/train/Saver#Methods), changing weight_file into the format of `save.ckpt-001000` will be helpful, the number `001000` depends on the name of checkpoint.

**Comment by leeyoshinari** [comment]
I also meet this problem. Can you tell me how to solve the problem, and how to change the write_version V1 or V2? @hizhangp @CompilerBian
