### ISSUE TITLE
[question] the reason of transpose?

### ISSUE THREAD

**Issue by ywpkwon** [hizhangp/yolo_tensorflow#11]
Hi, deeply thanks for sharing your work!

I found that there is a transpose in your code:
`net = tf.transpose(net, [0, 3, 1, 2], name='trans_31')`

This is where a `conv` layer gets flattened before `fc` layers. May I ask why transpose is there? Is this a standard way to do so? The YOLO paper recommends doing so?

**Comment by hizhangp** [comment]
In Darknet and Caffe, the `data_format` is `NCHW`(`[batch_size, channels, height, width]`), but in tensorflow, the default `data_format` is `NHWC`(`[batch_size, height, width, channels]`), so we need to permute the dimension to restore the pre-trained model correctly.

**Comment by ywpkwon** [comment]
Thanks for your answer! Can I also ask if you have tried to train from the scratch (not from the pre-trained `darknet` weights)? I tried to train pascal VOC from the scratch, but it seems not detecting. I am curious if there should be something.

**Comment by ywpkwon** [comment]
Oh, I see. We should pretrain the convolutional layers with ImageNet... (just found in the paper)
