### ISSUE TITLE
Hi ,  I have trained a model with your coded but there are something wrong in test.

### ISSUE THREAD

**Issue by YaoZhongtian** [hizhangp/yolo_tensorflow#16]
I have trained a model with your coded and the total loss was about 8 after 30000 iterations.  But when I test the trained weights, it cannot dectect objects correctly. For example , the confidents it given are lower than 0.01.

**Comment by hizhangp** [comment]
Did you train from scratch?

**Comment by YaoZhongtian** [comment]
I am so sorry. I don't know what the "scratch" mean.

**Comment by YaoZhongtian** [comment]
I think the reason must be the model can't converge . Could you please upload your ckpt file ? Thanks a lot!

**Comment by hizhangp** [comment]
I know, you should train your model from pretrained weight, or it's hard to converge.
You can download it from [README.md](https://github.com/hizhangp/yolo_tensorflow/blob/master/README.md) or a direct link [here](https://drive.google.com/file/d/0B5aC8pI-akZUNVFZMmhmcVRpbTA/view?usp=sharing).
