### ISSUE TITLE
Problems About model testing

### ISSUE THREAD

**Issue by SimonPrPr** [hizhangp/yolo_tensorflow#19]
I‘ve tried to use test.py to test the model trained by train.py. I rename the model to save.ckpt and use it as the weights to run the test.py. But it seems that test.py cannot open that file. Am i wrong in testing methods?

**Comment by SimonPrPr** [comment]
And there are three files generated per 1000 steps. which one should be used to run the test.py?

**Comment by leeyoshinari** [comment]
I meet this problem too. Can you tell me how to solve this problem?  thank you!
