### ISSUE TITLE
yolo config file

### ISSUE THREAD

**Issue by benn94** [hizhangp/yolo_tensorflow#21]
Hi,
I wonder how should i edit the config file.
What parameters should I make adjustment?

**Comment by hizhangp** [comment]
Feel free to edit `solver parameter` in config file, also you can modify `***_scale` to change the weight of each loss.

**Comment by BorinBangBang** [comment]
Thank you. May I know what is the GPU parameter? is it the number of gpu or a pointer to which gpu i am going to use?

**Comment by hizhangp** [comment]
`GPU = ''` means using CPU and `GPU = '0'` means using the first GPU.

**Comment by benn94** [comment]
What if I would like to use two GPU? How should I change it?

**Comment by hizhangp** [comment]
You can try to set `GPU = '0,1'` or `GPU = 'all'`.

**Comment by benn94** [comment]
Thank you.
