### ISSUE TITLE
python test.py

### ISSUE THREAD

**Issue by Abduoit** [hizhangp/yolo_tensorflow#27]
Hi, anyone can help

when I try python test.py I get the following error

abdulrahman@abdulrahman-ThinkPad-X230-Tablet:~/yolo_tensorflow$ python test.py 
Restoring weights from: data/weights/YOLO_small.ckpt
Average detecting time: 0.608s
Traceback (most recent call last):
  File "test.py", line 190, in <module>
    main()
  File "test.py", line 186, in main
    detector.image_detector(imname)
  File "test.py", line 161, in image_detector
    self.draw_result(image, result)
  File "test.py", line 43, in draw_result
    cv2.putText(img, result[i][0] + ' : %.2f' % result[i][5], (x - w + 5, y - h - 7), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 1, cv2.CV_AA)
AttributeError: 'module' object has no attribute 'CV_AA'

**Comment by hizhangp** [comment]
That's the opencv version error. Changing `cv2.CV_AA` to `cv2.LINE_AA' will fix it.

**Comment by Abduoit** [comment]
thx @hizhangp it works
