### ISSUE TITLE
training with new classes 

### ISSUE THREAD

**Issue by Abduoit** [hizhangp/yolo_tensorflow#28]
hi, 
how can train the model to recognize new type of images ?

**Comment by hizhangp** [comment]
Please refer to #1 and #3 .

**Comment by Abduoit** [comment]
Thanks for reply @hizhangp 
I have set of images but i don't know how to train the model with it?
could u plz tell me how to do it

**Comment by hizhangp** [comment]
Just change your images and labels into pascal_voc version.

**Comment by Abduoit** [comment]
I changed the images in VOC2007 folder and try to train it again
I got the following error

~/yolo_tensorflow$ python train.pyLoading gt_labels from: data/pascal_voc/cache/pascal_train_gt_labels.pkl
Appending horizontally-flipped training examples ...
Start training ...
OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /tmp/binarydeb/ros-kinetic-opencv3-3.2.0/modules/imgproc/src/imgwarp.cpp, line 3492
Traceback (most recent call last):
  File "train.py", line 164, in <module>
    main()
  File "train.py", line 158, in main
    solver.train()
  File "train.py", line 68, in train
    images, labels = self.data.get()
  File "/home/abdulrahman/yolo_tensorflow/utils/pascal_voc.py", line 35, in get
    images[count, :, :, :] = self.image_read(imname, flipped)
  File "/home/abdulrahman/yolo_tensorflow/utils/pascal_voc.py", line 47, in image_read
    image = cv2.resize(image, (self.image_size, self.image_size))
cv2.error: /tmp/binarydeb/ros-kinetic-opencv3-3.2.0/modules/imgproc/src/imgwarp.cpp:3492: error: (-215) ssize.width > 0 && ssize.height > 0 in function resize

**Comment by hizhangp** [comment]
Check your image.

**Comment by Abduoit** [comment]
How to check it, what do you mean ?

**Comment by hizhangp** [comment]
Some of your images are empty

**Comment by hizhangp** [comment]
I think you should check your image ...
