### ISSUE TITLE
How train the yolo networks without pre-train weight(don't use pre-train weights)

### ISSUE THREAD

**Issue by issxjl2015** [hizhangp/yolo_tensorflow#29]
I try to train the yolo networks, and don't use pre-train weight, but I get some error. 
that is my process:
1. changed '\yolo\config' WEIGHTS_FILE = os.path.join(DATA_PATH, 'weights', 'YOLO_small.ckpt')
    to WEIGHTS_FILE = None
2. 'parser.add_argument('--weights', default="YOLO_small.ckpt", type=str)' was comment out, because I want train yolo network without pre-train weights
3. 'cfg.WEIGHTS_FILE = os.path.join(cfg.WEIGHTS_DIR, args.weights)' was comment out, the reason is same as above

Please tell how, wo know my way is stupid, but I still want to try. Thx.

**Comment by hizhangp** [comment]
Please list your error, then I can help you ...

**Comment by issxjl2015** [comment]
OK, this is my complete error.

> I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:135] successfully opened CUDA library cublas64_80.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:135] successfully opened CUDA library cudnn64_5.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:135] successfully opened CUDA library cufft64_80.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:135] successfully opened CUDA library nvcuda.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:135] successfully opened CUDA library curand64_80.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GTX 960
major: 5 minor: 2 memoryClockRate (GHz) 1.266
pciBusID 0000:01:00.0
Total memory: 4.00GiB
Free memory: 3.33GiB
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:906] DMA: 0 
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:916] 0:   Y 
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 960, pci bus id: 0000:01:00.0)
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "BestSplits" device_type: "CPU"') for unknown op: BestSplits
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "CountExtremelyRandomStats" device_type: "CPU"') for unknown op: CountExtremelyRandomStats
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "FinishedNodes" device_type: "CPU"') for unknown op: FinishedNodes
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "GrowTree" device_type: "CPU"') for unknown op: GrowTree
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ReinterpretStringToFloat" device_type: "CPU"') for unknown op: ReinterpretStringToFloat
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "SampleInputs" device_type: "CPU"') for unknown op: SampleInputs
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ScatterAddNdim" device_type: "CPU"') for unknown op: ScatterAddNdim
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNInsert" device_type: "CPU"') for unknown op: TopNInsert
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNRemove" device_type: "CPU"') for unknown op: TopNRemove
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TreePredictions" device_type: "CPU"') for unknown op: TreePredictions
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "UpdateFertileSlots" device_type: "CPU"') for unknown op: UpdateFertileSlots
Loading gt_labels from: data\cache\pascal_train_gt_labels.pkl
Appending horizontally-flipped training examples ...
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 960, pci bus id: 0000:01:00.0)
Start training ...
W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\bfc_allocator.cc:217] Ran out of memory trying to allocate 1.60GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\bfc_allocator.cc:217] Ran out of memory trying to allocate 2.20GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\bfc_allocator.cc:217] Ran out of memory trying to allocate 1.15GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\bfc_allocator.cc:217] Ran out of memory trying to allocate 2.20GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\bfc_allocator.cc:217] Ran out of memory trying to allocate 2.31GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\bfc_allocator.cc:217] Ran out of memory trying to allocate 2.31GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\bfc_allocator.cc:217] Ran out of memory trying to allocate 2.31GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\bfc_allocator.cc:217] Ran out of memory trying to allocate 2.25GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\bfc_allocator.cc:217] Ran out of memory trying to allocate 2.26GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\bfc_allocator.cc:217] Ran out of memory trying to allocate 2.20GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Invalid argument: Nan in summary histogram for: train/boxes_delta_w
	 [[Node: train/boxes_delta_w = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](train/boxes_delta_w/tag, strided_slice_46/_97)]]
W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Invalid argument: Nan in summary histogram for: train/boxes_delta_w
	 [[Node: train/boxes_delta_w = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](train/boxes_delta_w/tag, strided_slice_46/_97)]]
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1022, in _do_call
    return fn(*args)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1004, in _run_fn
    status, run_metadata)
  File "C:\Anaconda3\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Nan in summary histogram for: train/boxes_delta_w
	 [[Node: train/boxes_delta_w = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](train/boxes_delta_w/tag, strided_slice_46/_97)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\yolo_tensorflow-20classer-10conv\yolo_tensorflow-master----github\train.py", line 157, in <module>
    main()
  File "E:\yolo_tensorflow-20classer-10conv\yolo_tensorflow-master----github\train.py", line 151, in main
    solver.train()
  File "E:\yolo_tensorflow-20classer-10conv\yolo_tensorflow-master----github\train.py", line 108, in train
    feed_dict=feed_dict)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 767, in run
    run_metadata_ptr)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Nan in summary histogram for: train/boxes_delta_w
	 [[Node: train/boxes_delta_w = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](train/boxes_delta_w/tag, strided_slice_46/_97)]]

Caused by op 'train/boxes_delta_w', defined at:
  File "E:\yolo_tensorflow-20classer-10conv\yolo_tensorflow-master----github\train.py", line 157, in <module>
    main()
  File "E:\yolo_tensorflow-20classer-10conv\yolo_tensorflow-master----github\train.py", line 147, in main
    yolo = YOLONet('train')
  File "E:\yolo_tensorflow-20classer-10conv\yolo_tensorflow-master----github\yolo\yolo_net.py", line 40, in __init__
    self.build_networks()
  File "E:\yolo_tensorflow-20classer-10conv\yolo_tensorflow-master----github\yolo\yolo_net.py", line 87, in build_networks
    self.loss = self.loss_layer(33, self.fc_32, self.labels)
  File "E:\yolo_tensorflow-20classer-10conv\yolo_tensorflow-master----github\yolo\yolo_net.py", line 435, in loss_layer
    tf.summary.histogram(self.phase + '/boxes_delta_w', boxes_delta[:, :, :, :, 2])
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\summary\summary.py", line 203, in histogram
    tag=scope.rstrip('/'), values=values, name=scope)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_logging_ops.py", line 139, in _histogram_summary
    name=name)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Nan in summary histogram for: train/boxes_delta_w
	 [[Node: train/boxes_delta_w = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](train/boxes_delta_w/tag, strided_slice_46/_97)]]

E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\cuda\cuda_gpu_executor.cc:637] Deallocating stream with pending work
[Finished in 26.0s with exit code 1]
[shell_cmd: python -u "E:\yolo_tensorflow-20classer-10conv\yolo_tensorflow-master----github\train.py"]
[dir: E:\yolo_tensorflow-20classer-10conv\yolo_tensorflow-master----github]
[path: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\libnvvp;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Anaconda3;C:\Anaconda3\Scripts;C:\Anaconda3\Library\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\MySQL\MySQL Utilities 1.6\;D:\python-3.5.3\Scripts\;D:\python-3.5.3\;C:\Users\Jinlong Xu\AppData\Local\Programs\Python\Python35\Scripts\;C:\Users\Jinlong Xu\AppData\Local\Programs\Python\Python35\;C:\Users\Jinlong Xu\AppData\Local\Microsoft\WindowsApps;C:\Windows\System32;]






The key error is "InvalidArgumentError (see above for traceback): Nan in summary histogram for: train/boxes_delta_w
	 [[Node: train/boxes_delta_w = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](train/boxes_delta_w/tag, strided_slice_46/_97)]]"

**Comment by issxjl2015** [comment]
Thx, and I has list my complete error in the site of github.com.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Peng Zhang<mailto:notifications@github.com>
发送时间: 2017年7月13日 12:44
收件人: hizhangp/yolo_tensorflow<mailto:yolo_tensorflow@noreply.github.com>
抄送: Jinlong Xu<mailto:issxjl2015@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [hizhangp/yolo_tensorflow] How train the yolo networks without pre-train weight(don't use pre-train weights) (#29)


Please list your error, then I can help you ...

―

**Comment by hizhangp** [comment]
`Nan in summary histogram for: train/boxes_delta_w`, maybe your labels are wrong.

**Comment by issxjl2015** [comment]
I don't think so, because I don't change any data, but change a train way without pre-train weights.
So I can sure other reason.

**Comment by issxjl2015** [comment]
I don't think so, because I don't change any data, but change a train way without pre-train weights.
So I can sure other reason.

**Comment by hizhangp** [comment]
I see, you should not train yolo from scratch, it will not converge.

**Comment by issxjl2015** [comment]
Why?  I am confused, must train the yolo network with pre-train weights, it will not converge ? ?

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Peng Zhang<mailto:notifications@github.com>
发送时间: 2017年7月13日 21:21
收件人: hizhangp/yolo_tensorflow<mailto:yolo_tensorflow@noreply.github.com>
抄送: Jinlong Xu<mailto:issxjl2015@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [hizhangp/yolo_tensorflow] How train the yolo networks without pre-train weight(don't use pre-train weights) (#29)


I see, you should not train yolo from scratch, it will not converge.

―

**Comment by issxjl2015** [comment]
Add, I want change the structure of yolo network, those is difference,  so I have not pre-train weights can be used.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Peng Zhang<mailto:notifications@github.com>
发送时间: 2017年7月13日 21:21
收件人: hizhangp/yolo_tensorflow<mailto:yolo_tensorflow@noreply.github.com>
抄送: Jinlong Xu<mailto:issxjl2015@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [hizhangp/yolo_tensorflow] How train the yolo networks without pre-train weight(don't use pre-train weights) (#29)


I see, you should not train yolo from scratch, it will not converge.

―

**Comment by hizhangp** [comment]
Please refer to [YOLO](https://arxiv.org/pdf/1506.02640.pdf).

**Comment by ddsrt-sean** [comment]
Hi   Sir,
Have you trained this without pre-weight, I meet it again。
how do you solve it ?
Thanks !
