### ISSUE TITLE
train my own pictures

### ISSUE THREAD

**Issue by NickYi1990** [hizhangp/yolo_tensorflow#3]
if i want to train this network on my own pictures, should i make my data the same format as VOC?

**Comment by hizhangp** [comment]
@NickYi1990 It's not necessary, you can write a data reader which is compact with your own data, just follow the API in `pascal_voc.py`. 
In other words, you only need to modify `load_labels` and `load_pascal_annotation` functions in `pascal_voc.py` to read your own data and annotation.

**Comment by NickYi1990** [comment]
Thanks!
