### ISSUE TITLE
Is there something wrong with the loss function？

### ISSUE THREAD

**Issue by xuhan1202** [hizhangp/yolo_tensorflow#44]
predict_boxes_tran = tf.stack(
                [(predict_boxes[..., 0] + offset) / self.cell_size,
                 (predict_boxes[..., 1] + offset_tran) / self.cell_size,
                 tf.square(predict_boxes[..., 2]),
                 tf.square(predict_boxes[..., 3])], axis=-1)

Why do you take the square of predicted h and w here?

And in
 boxes_delta = coord_mask * (predict_boxes - boxes_tran)
 
 You don't take the square root of predicted h and w.

So the output W and H of the network has already been taken root?

**Comment by hizhangp** [comment]
Please refer to the Yolo paper.
