### ISSUE TITLE
ValueError: Unknown format code 'f' for object of type 'str'

### ISSUE THREAD

**Issue by PPPxiaomoer** [hizhangp/yolo_tensorflow#46]
2018-03-31 21:29:02.437666: I tensorflow/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator: After 10024 get requests, put_count=10022 evicted_count=1000 eviction_rate=0.0997805 and unsatisfied allocation rate=0.109936
2018-03-31 21:29:02.437717: I tensorflow/core/common_runtime/gpu/pool_allocator.cc:259] Raising pool_size_limit_ from 100 to 110
Traceback (most recent call last):
  File "train.py", line 165, in <module>
    main()
  File "train.py", line 158, in main
    solver.train()
  File "train.py", line 90, in train
    train_timer.remain(step, self.max_iter))
ValueError: Unknown format code 'f' for object of type 'str'

**Comment by PPPxiaomoer** [comment]
ubuntu16.04+cuda8.0+cudnn5.1+tensorflow-gpu1.2

**Comment by marshellhu** [comment]
have you changed the program? why my gpu doesn't work?I use the same enviroment as upstairs.

**Comment by hizhangp** [comment]
Just comment line 90 in train.py to avoid the error. @PPPxiaomoer

**Comment by zyyhl** [comment]
I comment line 90 in train.py, but didn't solve the problem, still have the same problem

**Comment by zyyhl** [comment]
@hizhangp I comment line 90 in train.py, but didn't solve the problem, still have the same problem

**Comment by zhangming8** [comment]
I meet the same problem. Maybe you can try replace log_str=... with this:                     
log_str = '{} Epoch: {}, Step: {}, Learning rate: {}, Loss: {:5.3f}\nSpeed: {:.3f}s/iter,Load: {:.3f}s/iter, Remain: {}'.format(
                        datetime.datetime.now().strftime('%m-%d %H:%M:%S'),
                        self.data.epoch,
                        int(step),
                        round(self.learning_rate.eval(session=self.sess), 6),
                        loss,
                        train_timer.average_time,
                        load_timer.average_time,
                        train_timer.remain(step, self.max_iter))

**Comment by aidotayyy** [comment]
> 2018-03-31 21:29:02.437666: I tensorflow/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator: After 10024 get requests, put_count=10022 evicted_count=1000 eviction_rate=0.0997805 and unsatisfied allocation rate=0.109936
> 2018-03-31 21:29:02.437717: I tensorflow/core/common_runtime/gpu/pool_allocator.cc:259] Raising pool_size_limit_ from 100 to 110
> Traceback (most recent call last):
> File "train.py", line 165, in
> main()
> File "train.py", line 158, in main
> solver.train()
> File "train.py", line 90, in train
> train_timer.remain(step, self.max_iter))
> ValueError: Unknown format code 'f' for object of type 'str'

Try convert "train_timer.remain(step, self.max_iter))" to "float(train_timer.remain(step, self.max_iter))",maybe you can solve this problem
