### ISSUE TITLE
Test IOU

### ISSUE THREAD

**Issue by TingZhang08** [hizhangp/yolo_tensorflow#47]
I have run test.py successfully, and got a visualization picture of person.jpg.  And I also want to get the iou on VOC2007 test dataset. How could I do? Did anyone get the test iou on VOC2007 test dataset? Can you tell me ? Thank you.

**Comment by hizhangp** [comment]
I didn't include any code for calculate accuracy on test dataset, maybe you can refer to other repository in Github.
