### ISSUE TITLE
Running on python3.x

### ISSUE THREAD

**Issue by imian00** [hizhangp/yolo_tensorflow#7]
hi again!
recently I've spent time reading YOLO papers and trying to understand your codes.
now i think it's time to fine-tune the yolo and then make some modification on the basic structure of yolo.

but soon after I managed to prepare my own datasets from IMAGENET, I got another issue regarding python version.. I'm using python3.x and i have absolutely no idea about python2 or compatibility issue..

now i decided to first convert your codes to the codes that can be used in python3.x and then use them.
this weekend i'm just gonna convert all the python2-type print to python3-type print function and then i will execute the codes.
ex) print 'Hello world!' ----> print('Hello World') 

so.. can you tell me what kind of other issues i have to consider except for print function issues when py2.x -> py3.x ?

thanks in advance!

**Comment by hizhangp** [comment]
The difference between python3 and python2 in my code maybe only `print` and `/`(division). 

But I'm not quite sure, please leave a comment if you meet any other errors :)

**Comment by imian00** [comment]
ok I will try and then tell you errors if occur. thanks!

**Comment by zhangxiaodi** [comment]
Variable global_step already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:   i meet this error when i run the program of yolo-tensorflow？what should i do? can you give me any advice?

**Comment by hizhangp** [comment]
Did you already define `global_step` in other place?
