### ISSUE TITLE
InvalidArgumentError (see above for traceback): LossTensor is inf or nan : Tensor had NaN values          [[Node: train_op/CheckNumerics = CheckNumerics[T=DT_FLOAT, message="LossTensor is inf or nan", _device="/job:localhost/replica:0/task:0/device:CPU:0"](total_loss)]]

### ISSUE THREAD

**Issue by zx-code123** [hizhangp/yolo_tensorflow#79]
When i run on windows,it can run.However,when i run it on linux ,it occur the problem "InvalidArgumentError (see above for traceback): LossTensor is inf or nan : Tensor had NaN values
         [[Node: train_op/CheckNumerics = CheckNumerics[T=DT_FLOAT, message="LossTensor is inf or nan", _device="/job:localhost/replica:0/task:0/device:CPU:0"](total_loss)]]"
@hizhangp

**Comment by hx121071** [comment]
why?
