### ISSUE TITLE
Error occurs in training

### ISSUE THREAD

**Issue by pengwang823** [hizhangp/yolo_tensorflow#9]
AttributeError: 'YOLONet' object has no attribute 'loss'?
I check YONONet class and there is no 'loss' actually? is it wrong?

**Comment by hizhangp** [comment]
Bug fixed [here](https://github.com/hizhangp/yolo_tensorflow/blob/master/train.py#L77).

**Comment by pengwang823** [comment]
thanks for fix, let me have a try.

**Comment by TaihuLight** [comment]
Is this code only the implementation of yolov1 not for yolov2?

**Comment by hizhangp** [comment]
Yep, yolo v2 is not supported.
